<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Sophon.Downloader</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Version>2.1.3</Version>
	<Copyright>GesthosNetwork © 2026 All rights reserved.</Copyright>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishDir>..\bin\</PublishDir>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sophon\Sophon.csproj" />
  </ItemGroup>

  <Target Name="PostPublishCleanup" AfterTargets="Publish">
    <ItemGroup>
      <FilesToDelete Include="$(PublishDir)**\*.pdb" />
    </ItemGroup>

    <Delete Files="@(FilesToDelete)" />
    <RemoveDir Directories="$(ProjectDir)bin;$(ProjectDir)obj;$(ProjectDir)..\Sophon\bin;$(ProjectDir)..\Sophon\obj" />
  </Target>

</Project>
