<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Sophon.Downloader</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Version>2.1.6</Version>
    <Copyright>GesthosNetwork © 2026 All rights reserved.</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishDir>..\bin\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Options" Version="*" />
    <PackageReference Include="Google.Protobuf" Version="*" />
    <PackageReference Include="Hi3Helper.ZstdNet" Version="*" />
    <PackageReference Include="SharpHDiffPatch.Core" Version="*" />
    <PackageReference Include="System.IO.Hashing" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Sophon">
      <HintPath>..\Sophon\Sophon.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostPublishCleanup" AfterTargets="Publish">
    <ItemGroup>
      <FilesToDelete Include="$(PublishDir)**\*.pdb" />
    </ItemGroup>

    <Delete Files="@(FilesToDelete)" />
    <RemoveDir Directories="$(ProjectDir)bin;$(ProjectDir)obj;$(ProjectDir)..\Legacy\bin;$(ProjectDir)..\Legacy\obj" />
  </Target>

</Project>
